// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUAga2Gvx4O0Rqwn8JinRUW0SQQXSkdr0',
    appId: '1:162535504391:web:4ae7bdc4923827574648a2',
    messagingSenderId: '162535504391',
    projectId: 'palace-hotel-37af8',
    authDomain: 'palace-hotel-37af8.firebaseapp.com',
    storageBucket: 'palace-hotel-37af8.firebasestorage.app',
    measurementId: 'G-R180R2EB6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCodP6D7CQE8kX2tKwte1Iy2xvVnbjTnw',
    appId: '1:162535504391:android:e112cfabe275a72b4648a2',
    messagingSenderId: '162535504391',
    projectId: 'palace-hotel-37af8',
    storageBucket: 'palace-hotel-37af8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiOryJeHPVFuy8CzaJ6QQ9uc05K1Qp9fA',
    appId: '1:162535504391:ios:ac41acb34a815f564648a2',
    messagingSenderId: '162535504391',
    projectId: 'palace-hotel-37af8',
    storageBucket: 'palace-hotel-37af8.firebasestorage.app',
    iosBundleId: 'com.example.palaceSysteamManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiOryJeHPVFuy8CzaJ6QQ9uc05K1Qp9fA',
    appId: '1:162535504391:ios:ac41acb34a815f564648a2',
    messagingSenderId: '162535504391',
    projectId: 'palace-hotel-37af8',
    storageBucket: 'palace-hotel-37af8.firebasestorage.app',
    iosBundleId: 'com.example.palaceSysteamManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUAga2Gvx4O0Rqwn8JinRUW0SQQXSkdr0',
    appId: '1:162535504391:web:2fe23fa41ec92e7b4648a2',
    messagingSenderId: '162535504391',
    projectId: 'palace-hotel-37af8',
    authDomain: 'palace-hotel-37af8.firebaseapp.com',
    storageBucket: 'palace-hotel-37af8.firebasestorage.app',
    measurementId: 'G-NKLP4SZ2W0',
  );
}
